apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  namespace: final
spec:
  selector:
    app.kubernetes.io/name: app
    app.kubernetes.io/component: frontend
  ports:
  - port: 80
    targetPort: 81
  type: LoadBalancer