apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: final
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend