apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-data
  namespace: final
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: vol-080aaee6c5252cf0c